Build as a pure Python package
conda-forge/propka-feedstock pull request #20
Opened 2024-01-18 14:30 UTC by t20100

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR proposes to build this package as a pure Python package (which it is unless I missed something).
This would make it available for all Python versions/architectures (e.g., ppc64le).

2024-01-18 14:30 UTC, t20100 commented
@conda-forge-admin, please rerender

2024-01-18 16:59 UTC, tsenapathi approved these changes

2024-01-20 23:12 UTC, sobolevnrm requested changes
Can someone explain why the OS X and Windows builds were removed?  I'm sure there's a good reason but I want to make sure I understand before I approve.  Thanks!

2024-01-20 23:12 UTC, sobolevnrm commented on .azure-pipelines/azure-pipelines-osx.yml
Why was the OS X build removed?

2024-01-20 23:12 UTC, sobolevnrm commented on .azure-pipelines/azure-pipelines-win.yml
Why was the Windows build removed?

2024-01-22 10:57 UTC, t20100 commented
Since - unless I missed something - this is a pure Python package, it is built only once for all architecture, operating systems and versions of Python.
The build is done once on linux, but the generated package can be installed on different OSes.

2024-01-22 16:56 UTC, sobolevnrm commented
Got it.  Thanks!

2024-01-22 16:56 UTC, sobolevnrm approved these changes

2024-01-23 10:34 UTC, t20100 commented
If you are happy with it, I let you merge it, I don't have the right to do so.

2024-01-23 14:29 UTC, merged